/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PsdEditorRouteImport } from './routes/psd-editor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as Agent_studioRouteImport } from './routes/agent_studio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CanvasIdRouteImport } from './routes/canvas.$id'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const PsdEditorRoute = PsdEditorRouteImport.update({
  id: '/psd-editor',
  path: '/psd-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const Agent_studioRoute = Agent_studioRouteImport.update({
  id: '/agent_studio',
  path: '/agent_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/psd-editor': typeof PsdEditorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/psd-editor': typeof PsdEditorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/psd-editor': typeof PsdEditorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent_studio'
    | '/assets'
    | '/knowledge'
    | '/login'
    | '/psd-editor'
    | '/admin/dashboard'
    | '/canvas/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/knowledge'
    | '/login'
    | '/psd-editor'
    | '/admin/dashboard'
    | '/canvas/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent_studio'
    | '/assets'
    | '/knowledge'
    | '/login'
    | '/psd-editor'
    | '/admin/dashboard'
    | '/canvas/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  Agent_studioRoute: typeof Agent_studioRoute
  AssetsRoute: typeof AssetsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  PsdEditorRoute: typeof PsdEditorRoute
  CanvasIdRoute: typeof CanvasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/psd-editor': {
      id: '/psd-editor'
      path: '/psd-editor'
      fullPath: '/psd-editor'
      preLoaderRoute: typeof PsdEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_studio': {
      id: '/agent_studio'
      path: '/agent_studio'
      fullPath: '/agent_studio'
      preLoaderRoute: typeof Agent_studioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  Agent_studioRoute: Agent_studioRoute,
  AssetsRoute: AssetsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  PsdEditorRoute: PsdEditorRoute,
  CanvasIdRoute: CanvasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
